updates

diff --git a/scripts/manxf b/scripts/manxf
--- a/scripts/manxf
+++ b/scripts/manxf
@@ -1,38 +1,48 @@
 #!/usr/bin/env bash
-if ! pidof tmux &>/dev/null; then
-    tmux new -s scratch -d \; new -A -s master \; popup -E "$(which man) $1"
-    exit
-    # 1 1 1
-elif ! tmux list-sessions | grep -qi 'master' &>/dev/null && ! tmux list-sessions | grep -qi 'scratch' &>/dev/null && ! tmux list-sessions | grep -qi 'attached' &>/dev/null; then
-    tmux new -s scratch -d \; new -A -s master \; popup -E "$(which man) $1"
-    exit
-    # 1 0 1
-elif ! tmux list-sessions | grep -qi 'master' &>/dev/null && tmux list-sessions | grep -qi 'scratch' &>/dev/null && ! tmux list-sessions | grep -qi 'attached' &>/dev/null; then
-    tmux new -A -s master \; popup -E "$(which man) $1"
-    exit
-    # 1 1 0
-elif ! tmux list-sessions | grep -qi 'master' &>/dev/null && ! tmux list-sessions | grep -qi 'scratch' &>/dev/null && tmux list-sessions | grep -qi 'attached' &>/dev/null; then
-    tmux new -s scratch -d \; new -A -s master \; popup -E "$(which man) $1"
-    exit
-    # 1 0 0
-elif ! tmux list-sessions | grep -qi 'master' &>/dev/null && tmux list-sessions | grep -qi 'scratch' &>/dev/null && tmux list-sessions | grep -qi 'attached' &>/dev/null; then
-    tmux new -s master -d \; popup -E "$(which man) $1"
-    exit
-    # 0 1 1
-elif tmux list-sessions | grep -qi 'master' &>/dev/null && ! tmux list-sessions | grep -qi 'scratch' &>/dev/null && ! tmux list-sessions | grep -qi 'attached' &>/dev/null; then
-    tmux new -s scratch -d \; attach -t master \; popup -E "$(which man) $1"
-    exit
-    # 0 1 0
-elif tmux list-sessions | grep -qi 'master' &>/dev/null && ! tmux list-sessions | grep -qi 'scratch' &>/dev/null && tmux list-sessions | grep -qi 'attached' &>/dev/null; then
-    tmux new -s scratch -d \; popup -E "$(which man) $1"
-    exit
-    # 0 0 1
-elif tmux list-sessions | grep -qi 'master' &>/dev/null && tmux list-sessions | grep -qi 'scratch' &>/dev/null && ! tmux list-sessions | grep -qi 'attached' &>/dev/null; then
-    tmux attach -t master \; popup -E "$(which man) $1"
-    exit
-    # 0 0 0
-elif tmux list-sessions | grep -qi 'master' &>/dev/null && tmux list-sessions | grep -qi 'scratch' &>/dev/null && tmux list-sessions | grep -qi 'attached' &>/dev/null; then
-    tmux popup -E "$(which man) $1"
-    exit
+# check if fzf and apropos are installed, install if not
+requirements=("fzf" "apropos")
+
+for single in "${requirements[@]}"; do
+	if ! command -v "$single" &>/dev/null; then
+		printf "\n\t%s not found\n" "$single"
+	# do you want to install?
+		read -p "Would you like to install?: " -n 1 -r
+		if [[ "$REPLY" =~ ^[Yy]$ ]]; then
+			if command -v apt &>/dev/null; then
+				sudo apt install "$single"
+			elif command -v packman &>/dev/null; then
+				sudp pacman -S "$single"
+			else
+				printf "\n\t\tpackage not found\n\tuse your pkg manager to install %s\n" "$single" && exit 1
+			fi
+		else
+			printf "exiting program" && exit 0
+		fi
+	fi
+done
+
+# get command or keyword/phrase
+read -r -p "query: " query
+[[ "$query" ]] || exit 1
+
+# check if command is a builtin
+if [[ $(type -ta "$query" | head -1) == "builtin" ]]; then
+	tmux neww bash -c "man $(echo "$SHELL" | awk -F'/' '{print $NF}') | \less '+/$query\ \['" || exit 1
+
+# check if there is not a manpage
+elif [[ $(apropos "$query" &>/dev/null;echo "$?") == "16" ]]; then
+	printf "%s\n" "Unable to find man with keyword/phrase or builtin command to lookup." && exit 16
+
+# check if there is manpage
+elif [[ $(apropos "$query" &>/dev/null;echo "$?") == "0" ]]; then
+	selected=$(apropos "$query" | sort -u | fzf --border --margin=5% --color=dark --height=100% --reverse)
+
+# select and open manpage
+	if [[ "$selected" ]]; then
+		tmux neww bash -c "man $(echo -e  "$selected" | tr -d ' ' | awk -F'(' '{print $1"."$2}' | cut -d ')' -f 1)" || exit 1
+	fi
+else
+	printf "%s\n" "Unable to complete request for some reason" && exit 1
 fi
-exit
+exit 0
+
diff --git a/scripts/update-go b/scripts/update-go
--- a/scripts/update-go
+++ b/scripts/update-go
@@ -1,22 +1,56 @@
 #!/usr/bin/env bash
+# MIT License
+# Copyright (c) 2023 Jb Williams
+# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
+# The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
+# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 
-## dirty way of updating golang
-VERSION="$(curl https://go.dev/dl/ | grep -iE '<span>go[0-9].[0-9]{2}.[0-9]{1,2}.linux-amd64.tar.gz' | sed -e 's/<[^>]*.//g' | tr -d ' ')"
-echo "Your go version is $(go version 2>/dev/null)"
-read -p "Curl read Current Go Version as $VERSION : Would you like to Continue?(Y/n): " -n 1 -r
+# Get Golang Version and the Given Golang Hash for linux
+GO_DLPAGE="$(/usr/bin/curl https://go.dev/dl/ | /usr/bin/grep -iE 'href="/dl/go[0-9].[0-9]{2}.[0-9]{1,2}.linux-amd64.tar.gz"' -m 2 -A 6 | tail -7 | sed -e 's/<[^>]*.//g' | tr '\n' ' ')"
+GO_VERSION="$(printf "%s" "$GO_DLPAGE" | awk '{print $1}')"
+#GO_VERSION="$(echo "$GO_DLPAGE" | awk '{print $1}')"
+DL_HASH="$(printf "%s" "$GO_DLPAGE" | awk '{print $6}')"
+
+# Prompt User, asking if they want to continue
+#echo "Your version of golang is '$(go version 2>/dev/null)'"
+printf "%s!\n" "Your version of golang is '$(go version 2>/dev/null)'"
+read -p "Curl read the current version as $GO_VERSION : Would you like to Continue?(Y/n): " -n 1 -r
 if [[ "$REPLY" =~ ^[Yy]$ ]]; then
-    pushd /tmp || exit
-    wget https://go.dev/dl/"$VERSION"
-    tar xvfz "$VERSION"
-    if [[ -d /usr/local/go ]]; then
-        sudo rm -rf /usr/local/go
-        sudo mv go /usr/local/
-        rm "$VERSION"
-    else 
-        sudo mv go /usr/local/
-    fi
+	# Download to  /tmp dir
+    pushd /tmp || exit 1
+    /usr/bin/wget https://go.dev/dl/"$GO_VERSION"
+
+	# get sha256 of the file you are wanting to verify
+	if [[ -n "$GO_VERSION" ]] && [[ -f "$GO_VERSION" ]] && [[ ! -d "$GO_VERSION" ]]; then
+		TAR_HASH="$(shasum -a256 "$GO_VERSION" | awk '{print $1}')"
+	else
+		#echo "Unable to find the '.tar.gz', may have been an error downloading!"
+		printf "%s\n" "Unable to find the '.tar.gz', may have been an error downloading!"
+		popd || exit 1
+		exit 1
+	fi
+
+	# Check if the Golang .tar.gz's hash matches the given hash from the download page
+	if [[ "$DL_HASH" == "$TAR_HASH" ]]; then
+		# Decompress and move to proper place removing the older version if it exists
+		printf "%s!\n" "Hashes Match"
+		/usr/bin/tar xfz "$GO_VERSION"
+		if [[ -d /usr/local/go ]]; then
+			/usr/bin/sudo rm -rf /usr/local/go
+			/usr/bin/sudo mv go /usr/local/
+			/usr/bin/rm "$GO_VERSION"
+		else 
+			/usr/bin/sudo mv go /usr/local/
+			/usr/bin/rm "$GO_VERSION"
+		fi
+	else
+		# Abort if the .tar.gz's hash doesn't match the given hash from the download page
+		printf "%s!!!!\n" "HASHES DON'T MATCH!!! ABORTING!!"
+		rm "$GO_VERSION"
+	fi
     popd || return
 else
-    exit
+    exit 1
 fi
-exit
+exit 0
+
